[versions]
activityVersion = "1.10.1"
agp = "8.9.0"
barcodescanner = "4.3.0"
barcodeScanning = "17.3.0"
barcodeScanningVersion = "17.3.0"
cameraView = "1.4.1"
core = "3.5.1"
firebaseBom = "33.10.0"
fragment = "1.8.6"
itext7Core = "7.2.2"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
firebaseAuth = "23.2.0"
materialVersion = "1.12.0"
playServicesMlkitBarcodeScanning = "18.3.1"
roomRuntimeVersion = "2.6.1"
visionCommonVersion = "17.3.0"
zxingAndroidEmbedded = "4.3.0"

[libraries]
activity-v170 = { module = "androidx.activity:activity", version.ref = "activityVersion" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntimeVersion" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntimeVersion" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntimeVersion" }
barcode-scanning-v1730 = { module = "com.google.mlkit:barcode-scanning", version.ref = "barcodeScanning" }
barcodescanner = { module = "com.journeyapps:barcodescanner", version.ref = "barcodescanner" }
camera-core = { module = "androidx.camera:camera-core", version.ref = "cameraView" }
camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraView" }
camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraView" }
core = { module = "com.google.zxing:core", version.ref = "core" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
fragment = { module = "androidx.fragment:fragment", version.ref = "fragment" }
google-firebase-auth = { module = "com.google.firebase:firebase-auth" }
itext7-core = { module = "com.itextpdf:itext7-core", version.ref = "itext7Core" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuth" }
material-v190 = { module = "com.google.android.material:material", version.ref = "materialVersion" }
mlkit-barcode-scanning = { module = "com.google.mlkit:barcode-scanning", version.ref = "barcodeScanningVersion" }
mlkit-vision-common = { module = "com.google.mlkit:vision-common", version.ref = "visionCommonVersion" }
play-services-mlkit-barcode-scanning = { module = "com.google.android.gms:play-services-mlkit-barcode-scanning", version.ref = "playServicesMlkitBarcodeScanning" }
zxing-android-embedded = { module = " com.journeyapps:zxing-android-embedded", version.ref = "zxingAndroidEmbedded" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

